apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollout-bluegreen
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/gowdasagar06/ArgoCD-3-Tier-Deployment.git
    targetRevision: HEAD
    path: blue-green-deploy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectSyncOnlyAnnotations=true
  ignoreDifferences:
    - group: argoproj.io
      kind: Rollout
      jsonPointers:
        - /spec/replicas
