apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        # image: nginx:latest
        # image: gowdasagar/nginx-blue-green:blue-v1
        image: gowdasagar/nginx-blue-green:green-v2
        ports:
        - containerPort: 80

